Changes to the README, mostly on the CDS data store
EUREC4A-UK/lagtraj pull request #194
Opened 2023-01-04 18:22 UTC by sjboeing

2023-01-04 21:17 UTC, sjboeing commented
Hi @leifdenby: I have added Ralph's suggested changes to the README here. Let me know if it needs a changelog (it is only changes to the README, not the code itself).

2023-01-05 08:50 UTC, sjboeing commented
Addresses #193.

2023-01-05 12:08 UTC, leifdenby requested changes
Thanks for doing this. Apart for a small typo this looks good to me :)

2023-01-05 12:08 UTC, leifdenby commented on README.md
> +You can monitor the status of your requests via the [CDS requests page](ihttps://cds.climate.copernicus.eu).
I think you have a superfluous `i` at the beginning of the link, should be `https://` I think

2023-01-05 13:35 UTC, sjboeing commented
Thanks @leifdenby: happens to me every once in a while with vi!

2023-01-05 14:31 UTC, leifdenby commented
Looks good to merge. I would update the changelog too, keeps a record of the work you've done :) Also, there was a typo in the readme before. You've made the readme better, so that's an "improvement" to add to the changelog

2023-01-10 12:39 UTC, merged